export const FETCH_LIST = 'FETCH_LIST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL';


export const FETCH_PATIENT_DETAIL = 'FETCH_PATIENT_DETAIL';
export const FETCH_PATIENT_DETAIL_SUCCESS = 'FETCH_PATIENT_DETAIL_SUCCESS';
export const FETCH_PATIENT_DETAIL_FAIL = 'FETCH_PATIENT_DETAIL_FAIL';

export const ADD_PATIENT = 'ADD_PATIENT';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAIL = 'ADD_PATIENT_FAIL';

export const UPDATE_PATIENT_DETAIL = 'UPDATE_PATIENT_DETAIL';
export const UPDATE_PATIENT_DETAIL_SUCCESS = 'UPDATE_PATIENT_DETAIL_SUCCESS';
export const UPDATE_PATIENT_DETAIL_FAIL = 'UPDATE_PATIENT_DETAIL_FAIL';

export const DELETE_PATIENT = 'DELETE_PATIENT';
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS';
export const DELETE_PATIENT_FAIL = 'DELETE_PATIENT_FAIL';

export const INIT_UPDATE_PATIENT_FORM = 'INIT_UPDATE_PATIENT_FORM';
export const RESET_PATIENT_FORM = 'RESET_PATIENT_FORM';