export const FETCH_SCHEDULE = 'FETCH_SCHEDULE';
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS';
export const FETCH_SCHEDULE_FAIL = 'FETCH_SCHEDULE_FAIL';

export const FETCH_SCHEDULE_DETAIL = 'FETCH_SCHEDULE_DETAIL';
export const FETCH_SCHEDULE_DETAIL_SUCCESS = 'FETCH_SCHEDULE_DETAIL_SUCCESS';
export const FETCH_SCHEDULE_DETAIL_FAIL = 'FETCH_SCHEDULE_DETAIL_FAIL';

export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const ADD_SCHEDULE_SUCCESS = 'ADD_SCHEDULE_SUCCESS';
export const ADD_SCHEDULE_FAIL = 'ADD_SCHEDULE_FAIL';

export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS';
export const UPDATE_SCHEDULE_FAIL = 'UPDATE_SCHEDULE_FAIL';

export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_FAIL = 'DELETE_SCHEDULE_FAIL';